'use strict';

(function () {
  var PHOTOS_QUANTITY = 25;
  var RANDOM_PHOTOS_QUANTITY = 10;
  var ESC_KEY = 'Escape';
  var TIMEOUT_DOWNLOAD_ERRORR = 4000;
  var DEBOUNCE_INTERVAL = 500; // ms
  var COMMENTS_INSTALLMENT = 5;
  window.consts = {
    PHOTOS_QUANTITY: PHOTOS_QUANTITY,
    RANDOM_PHOTOS_QUANTITY: RANDOM_PHOTOS_QUANTITY,
    ESC_KEY: ESC_KEY,
    TIMEOUT_DOWNLOAD_ERRORR: TIMEOUT_DOWNLOAD_ERRORR,
    DEBOUNCE_INTERVAL: DEBOUNCE_INTERVAL,
    COMMENTS_INSTALLMENT: COMMENTS_INSTALLMENT
  };
})();
